name: Docker Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    name: Building image
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker login
        if: env.VERSION
        uses: docker/login-action@v3
        with:
          registry: apiubu02.m2mservices.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract version from Git
        id: get_version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t apiubu02.m2mservices.com/test_projects:staging_latest -t apiubu02.m2mservices.com/test_projects:staging_${{ env.version }} -f TestProject/TestProject/Dockerfile .
          docker push apiubu02.m2mservices.com/test_projects:staging_latest
          docker push apiubu02.m2mservices.com/test_projects:staging_${{ env.version }}
