name: CD
on:
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName 185.201.80.253
          Port 43389
          User dev
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Run server commands
      run: ssh -vvv staging -p 43389 'echo 'devQq12345678' | sudo -kS ls; cd; ./run pull m2mtunnelrelay; ./run up -d m2mtunnelrelay'
