name: CD
on:
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName 10.10.12.200
          Port 43389
          User dev
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Run server commands
      run: ssh staging -p 43389 'echo "testing" > testfile1276'
